# Generated by Django 5.2 on 2025-04-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitupdate',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='robot.transit'),
        ),
    ]
