# Generated by Django 5.2 on 2025-04-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_transitupdate_transit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='robot.package'),
        ),
    ]
