# Generated by Django 5.2 on 2025-04-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_transit_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='robot.package'),
        ),
    ]
